import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Meu Boyler Plate",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (

    <div>
        <p>MAIS PRODUTOS</p>
        {children}
        <p>MAIS PRODUTOS</p>
    </div>
  );
}
