import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Produtos",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body>
        <p>Mais Produtos</p>
        {children}
        <p>Mais Produtos</p>
      </body>
    </html>
  );
}
