import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "PRODUTO",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <div>
      <p>MAIS PRODUTOS</p>
      {children}
      <p>MAIS PRODUTOS</p>
    </div>
  );
}
